### ISSUE TITLE
Failed to activate the anime-dark-ui package

### ISSUE THREAD

**Issue by RetricSu** [Knose1/anime-dark-ui#7]
whenever i change to anime-dark theme, it just says : Failed to activate the anime-dark-ui package, Cannot read property 'style' of null

**Comment by Knose1** [comment]
@RetricSu 
Hi, thanks for this issue. There isn't many details (for example the line where the error occure) so can you do the following steps :
1. Can you screen the error message on atom and in the dev console (ctrl + maj + i)
2. The theme add an element in the <body> for the background transition so try reload atom

**Comment by RetricSu** [comment]
![wechatimg59](https://user-images.githubusercontent.com/23436060/47062044-b9953400-d206-11e8-8d7a-f4a23dbeb37a.jpeg)
sorry, after I reload the atom, it somehow fixed the problem. and now I can't repeat the error, only got the screen img above, forget to screen the dev console...

**Comment by Knose1** [comment]
No problem, I think I fonded why does this bug occure : when dowloading the package and then loading it, the element (for the transition) is not added and then it does the error you have. Unfortunately I don't think that this bug can be resolved, instead i'm going to add something to inform peopls about that bug.
